db-keycloak:
    image: postgres
    volumes:
      - ./keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak1234
  
keycloak:
  image: quay.io/keycloak/keycloak:26.1.3
  command: start
  environment:
    KC_HOSTNAME: localhost
    KC_HOSTNAME_PORT: 20000
    KC_HOSTNAME_STRICT_BACKCHANNEL: false
    KC_HTTP_ENABLED: true
    KC_HOSTNAME_STRICT_HTTPS: false
    KC_HEALTH_ENABLED: true
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin1234
    KC_DB: postgres
    KC_DB_URL: jdbc:postgresql://db-keycloak/keycloakdb
    KC_DB_USERNAME: keycloak
    KC_DB_PASSWORD: keycloak1234
  ports:
    - 20000:8080
  depends_on:
    - db-keycloak